# permissions for end users to view podroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podroute-viewer-role
rules:
- apiGroups:
  - cache.quay.io
  resources:
  - podroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.quay.io
  resources:
  - podroutes/status
  verbs:
  - get
