# permissions for end users to edit podroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podroute-editor-role
rules:
- apiGroups:
  - cache.quay.io
  resources:
  - podroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.quay.io
  resources:
  - podroutes/status
  verbs:
  - get
